# Generated by Django 3.2.13 on 2023-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Pakages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField(max_length=100)),
                ('Days', models.IntegerField(max_length=20)),
                ('Nights', models.IntegerField(max_length=20)),
                ('Locations', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
