# Generated by Django 3.2.13 on 2023-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230204_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
