# Generated by Django 3.2.13 on 2023-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_pakages',
            name='Days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour_pakages',
            name='Nights',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour_pakages',
            name='price',
            field=models.IntegerField(),
        ),
    ]
